// prompt.go drives the interactive flag-collection used when EnsureExists
// hits a missing gh-optivem.yaml on a TTY. The interactive surface is
// deliberately narrower than the non-interactive `config init` command:
// frontend-lang is hardcoded to `typescript`, deploy is hardcoded to
// `docker`, tier paths fall through to the defaults baked into
// resolvePathFlagsForYAML (the flat scaffold layout), and the user is
// asked only the fields with no good default — owner, repo, system-name,
// arch, repo-strategy, lang, test-lang, project-url, license. A banner
// header prepended to the generated YAML points the operator at the
// defaulted fields and recommends running `gh optivem config validate`
// after review.
//
// test-lang is asked separately from the impl lang (monolith /
// backend): a Java monolith may be exercised by TypeScript Playwright
// tests, a .NET backend by Java RestAssured tests, etc. The earlier
// fall-through to the impl lang has been removed; --test-lang is now
// required at the flag layer as well, so prompt and flag stay in
// lockstep.
//
// Owner/repo are always asked: in environments with multiple accounts
// (personal + org), the `git remote get-url origin` of the current
// working directory is not a reliable proxy for the operator's intent.
//
// Each answer is validated against the same validator the `config init`
// flag path runs (see interactive-validation-parity feedback): format
// validators are the shared internal/config functions, and owner +
// project-URL existence are checked via config.CheckOwnerExists /
// config.CheckProjectExists. A bad value re-asks just that field rather
// than discarding the whole session.
package configinit

import (
	"bufio"
	"fmt"
	"io"
	"strconv"
	"strings"

	"github.com/optivem/gh-optivem/internal/approval"
	"github.com/optivem/gh-optivem/internal/config"
	"github.com/optivem/gh-optivem/internal/projectconfig"
)

// defaultLicense is the prompt default for the license question. Matches
// bindYAMLAffectingFlags's --license default so the interactive and
// flag-driven paths produce identical YAML when the operator accepts the
// default.
const defaultLicense = projectconfig.LicenseMIT

// Banner is the comment header prepended to YAML generated by the
// interactive recovery flow. Single-sourced here so the prompt copy and
// the writer share one constant.
const Banner = `# gh-optivem.yaml — generated by ` + "`gh optivem config init`" + ` (interactive recovery).
# Review the following fields and run ` + "`gh optivem config validate`" + `:
#   - project.url
#       Your GitHub Projects board URL.
#   - repo-strategy
#       mono-repo (default) or multi-repo.
#   - system.lang / system.backend.lang
#       java, dotnet, or typescript.
#   - *.path fields
#       Assume the flat scaffold layout. Adjust to match your repo.
#   - license
#       SPDX-like key written to LICENSE. mit if you didn't pick one.
#   - deploy
#       docker today; cloud-run lands when its scaffold path stabilises.

`

// Prompt collects the slim interactive `config init` flag set and
// returns a populated RawFlags. Reads one line at a time from in;
// echoes prompts and validator errors to out. Re-asks the same field on
// validation failure; prior answers in the session are kept. Returns
// io.EOF (wrapped) if stdin closes mid-session, so callers can fall back
// to the terse error.
//
// Callers print their own context-appropriate banner before invoking
// Prompt (EnsureExists says "no gh-optivem.yaml at X; creating one
// interactively"; `config init` says "Creating X" or "Overwriting X").
// Prompt itself prints only the operational hint shared by both paths.
func Prompt(in io.Reader, out io.Writer) (*config.RawFlags, error) {
	r := bufio.NewReader(in)
	f := &config.RawFlags{}

	fmt.Fprintln(out, "Enter values for each prompt; bad input re-asks.")

	if err := askOwner(r, out, f); err != nil {
		return nil, err
	}
	if err := askRepo(r, out, f); err != nil {
		return nil, err
	}
	if err := askSystemName(r, out, f); err != nil {
		return nil, err
	}
	if err := askArch(r, out, f); err != nil {
		return nil, err
	}
	if err := askRepoStrategy(r, out, f); err != nil {
		return nil, err
	}
	if err := askLang(r, out, f); err != nil {
		return nil, err
	}
	if err := askTestLang(r, out, f); err != nil {
		return nil, err
	}
	if err := askProjectURL(r, out, f); err != nil {
		return nil, err
	}
	if err := askLicense(r, out, f); err != nil {
		return nil, err
	}

	applyDefaults(f)
	return f, nil
}

func askOwner(r *bufio.Reader, out io.Writer, f *config.RawFlags) error {
	return ask(r, out, "GitHub owner (user or org), e.g. acme", func(v string) (string, error) {
		if msg := config.ValidateOwnerFormat(v); msg != "" {
			return "", fmt.Errorf("%s", msg)
		}
		if err := config.CheckOwnerExists(v); err != nil {
			return "", err
		}
		f.Owner = v
		return v, nil
	})
}

func askRepo(r *bufio.Reader, out io.Writer, f *config.RawFlags) error {
	return ask(r, out, "Repository name (without owner prefix), e.g. page-turner", func(v string) (string, error) {
		if msg := config.ValidateRepoFormat(v); msg != "" {
			return "", fmt.Errorf("%s", msg)
		}
		f.Repo = v
		return v, nil
	})
}

// askSystemName collects the human-readable system label that drives
// templating (e.g. "Page Turner"). Validated with the same rule
// `gh optivem init` applies to its --system-name flag.
func askSystemName(r *bufio.Reader, out io.Writer, f *config.RawFlags) error {
	return ask(r, out, `System name, e.g. "Page Turner"`, func(v string) (string, error) {
		if msg := config.ValidateSystemName(v); msg != "" {
			return "", fmt.Errorf("%s", msg)
		}
		f.SystemName = v
		return v, nil
	})
}

// langChoices is the shared option list for monolith/backend lang
// prompts. Must stay in sync with config.ValidateBackendLang — the
// accept callback still runs that validator so a drift here surfaces
// rather than landing in the YAML.
var langChoices = []string{"java", "dotnet", "typescript"}

// licenseChoices enumerates the SPDX-like keys IsValidLicense accepts.
// Order matters for the numbered prompt; defaultLicense is highlighted
// as the ENTER default.
var licenseChoices = []string{"mit", "apache-2.0", "gpl-3.0", "bsd-2-clause", "bsd-3-clause", "unlicense"}

// askLicense collects the license key for the scaffolded LICENSE file.
// ENTER selects defaultLicense, parallel to the flag default in
// bindYAMLAffectingFlags.
func askLicense(r *bufio.Reader, out io.Writer, f *config.RawFlags) error {
	dflt := indexOf(licenseChoices, defaultLicense) + 1
	return askChoice(r, out, "License", licenseChoices, dflt, func(v string) error {
		if !projectconfig.IsValidLicense(v) {
			return fmt.Errorf("must be one of mit, apache-2.0, gpl-3.0, bsd-2-clause, bsd-3-clause, unlicense")
		}
		f.License = v
		return nil
	})
}

func askArch(r *bufio.Reader, out io.Writer, f *config.RawFlags) error {
	return askChoice(r, out, "Architecture", []string{"monolith", "multitier"}, 0, func(v string) error {
		if msg := config.ValidateArch(v); msg != "" {
			return fmt.Errorf("%s", msg)
		}
		f.Arch = v
		return nil
	})
}

func askRepoStrategy(r *bufio.Reader, out io.Writer, f *config.RawFlags) error {
	return askChoice(r, out, "Repo strategy", []string{"monorepo", "multirepo"}, 0, func(v string) error {
		if msg := config.ValidateRepoStrategy(v); msg != "" {
			return fmt.Errorf("%s", msg)
		}
		f.RepoStrategy = v
		return nil
	})
}

// askLang asks one language question that matches the chosen arch:
// monolith → --monolith-lang; multitier → --backend-lang. On multitier
// the frontend lang is hardcoded to typescript in applyDefaults (today's
// only valid value); when frontend-lang accepts more than typescript,
// add a matching prompt here.
func askLang(r *bufio.Reader, out io.Writer, f *config.RawFlags) error {
	switch f.Arch {
	case "monolith":
		return askChoice(r, out, "Monolith language", langChoices, 0, func(v string) error {
			if msg := config.ValidateBackendLang(v); msg != "" {
				return fmt.Errorf("%s", msg)
			}
			f.Lang = v
			return nil
		})
	case "multitier":
		return askChoice(r, out, "Backend language", langChoices, 0, func(v string) error {
			if msg := config.ValidateBackendLang(v); msg != "" {
				return fmt.Errorf("%s", msg)
			}
			f.BackendLang = v
			return nil
		})
	}
	return fmt.Errorf("unreachable: arch %q passed validation but no lang branch", f.Arch)
}

// askTestLang collects the system-test language. Asked as its own
// question rather than defaulted to the impl lang: the test tier is
// architecturally independent (Java monolith + TypeScript Playwright,
// .NET backend + Java RestAssured, etc.). Reuses ValidateBackendLang —
// the format check is the same enum (java/dotnet/typescript) the impl
// lang accepts.
func askTestLang(r *bufio.Reader, out io.Writer, f *config.RawFlags) error {
	return askChoice(r, out, "System-test language", langChoices, 0, func(v string) error {
		if msg := config.ValidateBackendLang(v); msg != "" {
			return fmt.Errorf("%s", msg)
		}
		f.TestLang = v
		return nil
	})
}

// askProjectURL gates the GitHub Project URL behind a y/n question via
// promptio.ConfirmYN (the project-wide y/n helper, no Enter-default).
// "no" leaves f.ProjectURL empty so the flag-path semantics for an
// unset --project-url still apply. "yes" asks for the URL with full
// format + existence validation, re-asking just the URL on a bad value
// rather than discarding the whole session.
func askProjectURL(r *bufio.Reader, out io.Writer, f *config.RawFlags) error {
	has, err := approval.Confirm(pkgApproval, approval.CategoryPrompt, r, out, "  Do you have an existing GitHub Project?")
	if err != nil {
		return fmt.Errorf("read project URL gate: %w", err)
	}
	if !has {
		return nil
	}
	return ask(r, out, "GitHub Project URL, e.g. https://github.com/orgs/acme/projects/1", func(v string) (string, error) {
		if msg := config.ValidateProjectURLFormat(v); msg != "" {
			return "", fmt.Errorf("%s", msg)
		}
		if err := config.CheckProjectExists(v); err != nil {
			return "", err
		}
		f.ProjectURL = v
		return v, nil
	})
}

// indexOf returns the index of want in xs, or -1 if absent.
func indexOf(xs []string, want string) int {
	for i, x := range xs {
		if x == want {
			return i
		}
	}
	return -1
}

// applyDefaults fills the fields the prompt does NOT ask for and that
// are NOT already defaulted by config.resolvePathFlagsForYAML (tier
// paths). Today that's frontend-lang on multitier (typescript is the
// only valid value) and deploy (docker; cloud-run is in development —
// prompt for it when a real choice exists).
// TODO: prompt for frontend-lang when more than typescript is valid.
// TODO: prompt for deploy when cloud-run ships.
func applyDefaults(f *config.RawFlags) {
	f.Deploy = projectconfig.DeployDocker
	if f.Arch == "multitier" {
		f.FrontendLang = "typescript"
	}
}

// ask prints a single prompt and loops until accept returns nil. The
// caller's accept closure both validates and stores the value into the
// RawFlags. EOF (no more input — pipe closed, ^D, tests running out of
// fixture lines) is surfaced verbatim so the missing-file recovery can
// abort with the terse-error fallback rather than spin forever.
func ask(r *bufio.Reader, out io.Writer, label string, accept func(string) (string, error)) error {
	for {
		fmt.Fprintf(out, "  %s: ", label)
		line, err := r.ReadString('\n')
		if err != nil {
			return fmt.Errorf("read %s: %w", label, err)
		}
		v := strings.TrimSpace(line)
		if v == "" {
			fmt.Fprintln(out, "    value cannot be empty")
			continue
		}
		if _, err := accept(v); err != nil {
			fmt.Fprintf(out, "    %s\n", err)
			continue
		}
		return nil
	}
}

// askChoice prints a numbered list of options and reads an integer
// selection (1..N). The chosen label is echoed back ("  → java") and
// passed to accept, which still runs the same validator the flag path
// uses so a drift between the choices slice and the validator surfaces
// at runtime. defaultIdx = 0 means no default (empty input re-asks);
// defaultIdx ∈ [1, len(choices)] makes ENTER select choices[defaultIdx-1]
// and adds a "(default)" marker next to that option. Out-of-range or
// non-numeric input re-asks without consuming the rest of the script.
func askChoice(r *bufio.Reader, out io.Writer, label string, choices []string, defaultIdx int, accept func(string) error) error {
	if defaultIdx < 0 || defaultIdx > len(choices) {
		return fmt.Errorf("askChoice %q: defaultIdx %d out of range [0, %d]", label, defaultIdx, len(choices))
	}
	for {
		fmt.Fprintf(out, "  %s:\n", label)
		for i, c := range choices {
			if defaultIdx == i+1 {
				fmt.Fprintf(out, "    [%d] %s (default)\n", i+1, c)
			} else {
				fmt.Fprintf(out, "    [%d] %s\n", i+1, c)
			}
		}
		if defaultIdx > 0 {
			fmt.Fprintf(out, "  Choose [1-%d, ENTER = %d]: ", len(choices), defaultIdx)
		} else {
			fmt.Fprintf(out, "  Choose [1-%d]: ", len(choices))
		}
		line, err := r.ReadString('\n')
		if err != nil {
			return fmt.Errorf("read %s: %w", label, err)
		}
		v := strings.TrimSpace(line)
		var n int
		if v == "" {
			if defaultIdx == 0 {
				fmt.Fprintf(out, "    please enter a number between 1 and %d\n", len(choices))
				continue
			}
			n = defaultIdx
		} else {
			parsed, err := strconv.Atoi(v)
			if err != nil || parsed < 1 || parsed > len(choices) {
				fmt.Fprintf(out, "    please enter a number between 1 and %d\n", len(choices))
				continue
			}
			n = parsed
		}
		chosen := choices[n-1]
		fmt.Fprintf(out, "    → %s\n", chosen)
		if err := accept(chosen); err != nil {
			fmt.Fprintf(out, "    %s\n", err)
			continue
		}
		return nil
	}
}
