// prompt.go drives the interactive flag-collection used when EnsureExists
// hits a missing gh-optivem.yaml on a TTY. The interactive surface is
// deliberately narrower than the non-interactive `config init` command:
// owner/repo are inferred from `git remote get-url origin`, path fields
// default to the flat scaffold layout, frontend-lang is hardcoded to
// `react`, and the user is asked only the four fields with no good
// default — arch, repo-strategy, lang, project-url. A banner header
// prepended to the generated YAML points the operator at the defaulted
// fields and recommends running `gh optivem config validate` after
// review.
//
// Each answer is validated against the same validator the `config init`
// command runs after Cobra parsing, so a bad value re-asks just that
// field rather than discarding the whole session.
package configinit

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/optivem/gh-optivem/internal/config"
	"github.com/optivem/gh-optivem/internal/projectconfig"
)

// defaultLicense is the prompt default for the license question. Matches
// bindYAMLAffectingFlags's --license default so the interactive and
// flag-driven paths produce identical YAML when the operator accepts the
// default.
const defaultLicense = projectconfig.LicenseMIT

// Banner is the comment header prepended to YAML generated by the
// interactive recovery flow. Single-sourced here so the prompt copy and
// the writer share one constant.
const Banner = `# gh-optivem.yaml — generated by ` + "`gh optivem config init`" + ` (interactive recovery).
# Review the following fields and run ` + "`gh optivem config validate`" + `:
#   - project.url
#       Your GitHub Projects board URL.
#   - repo_strategy
#       mono-repo (default) or multi-repo.
#   - system.lang / system.backend.lang
#       java, dotnet, or typescript.
#   - *.path fields
#       Assume the flat scaffold layout. Adjust to match your repo.
#   - license
#       SPDX-like key written to LICENSE. mit if you didn't pick one.
#   - deploy
#       docker today; cloud-run lands when its scaffold path stabilises.

`

// Default path values applied to whatever the user did not supply.
// Mirror config.resolveScaffoldPaths — the layout the scaffolder itself
// produces — so a freshly-prompted YAML matches what `gh optivem init`
// would have generated for the same arch.
const (
	defaultSystemTestPath = "system-test"
	defaultStubsPath      = "external-systems/external-stub"
	defaultSimulatorsPath = "external-systems/external-real-sim"
	defaultSystemPath     = "system"
	defaultBackendPath    = "backend"
	defaultFrontendPath   = "frontend"
)

// Prompt collects the slim interactive `config init` flag set and
// returns a populated RawFlags. Reads one line at a time from in;
// echoes prompts and validator errors to out. Re-asks the same field on
// validation failure; prior answers in the session are kept. Returns
// io.EOF (wrapped) if stdin closes mid-session, so callers can fall back
// to the terse error.
//
// owner/repo are inferred from the local git remote when available
// (announced on stdout so the operator can Ctrl-C if origin points at
// the wrong remote). On inference failure both fields are prompted with
// the same validators the inferred-path would have applied.
func Prompt(in io.Reader, out io.Writer) (*config.RawFlags, error) {
	r := bufio.NewReader(in)
	f := &config.RawFlags{}

	fmt.Fprintln(out, "No gh-optivem.yaml found — let's create one. Enter values for each prompt; bad input re-asks.")

	cwd, _ := os.Getwd()
	if owner, repo, ok := InferOwnerRepo(cwd); ok {
		f.Owner = owner
		f.Repo = repo
		fmt.Fprintf(out, "Inferred owner=%s, repo=%s from git remote origin\n", owner, repo)
	} else {
		if err := askOwner(r, out, f); err != nil {
			return nil, err
		}
		if err := askRepo(r, out, f); err != nil {
			return nil, err
		}
	}

	if err := askSystemName(r, out, f); err != nil {
		return nil, err
	}
	if err := askArch(r, out, f); err != nil {
		return nil, err
	}
	if err := askRepoStrategy(r, out, f); err != nil {
		return nil, err
	}
	if err := askLang(r, out, f); err != nil {
		return nil, err
	}
	if err := askProjectURL(r, out, f); err != nil {
		return nil, err
	}
	if err := askLicense(r, out, f); err != nil {
		return nil, err
	}

	applyDefaults(f)
	return f, nil
}

func askOwner(r *bufio.Reader, out io.Writer, f *config.RawFlags) error {
	return ask(r, out, "GitHub owner (user or org)", func(v string) (string, error) {
		if msg := config.ValidateOwnerFormat(v); msg != "" {
			return "", fmt.Errorf("%s", msg)
		}
		f.Owner = v
		return v, nil
	})
}

func askRepo(r *bufio.Reader, out io.Writer, f *config.RawFlags) error {
	return ask(r, out, "Repository name (without owner prefix)", func(v string) (string, error) {
		if msg := config.ValidateRepoFormat(v); msg != "" {
			return "", fmt.Errorf("%s", msg)
		}
		f.Repo = v
		return v, nil
	})
}

// askSystemName collects the human-readable system label that drives
// templating (e.g. "Page Turner"). Validated with the same rule
// `gh optivem init` applies to its --system-name flag.
func askSystemName(r *bufio.Reader, out io.Writer, f *config.RawFlags) error {
	return ask(r, out, `System name, e.g. "Page Turner"`, func(v string) (string, error) {
		if msg := config.ValidateSystemName(v); msg != "" {
			return "", fmt.Errorf("%s", msg)
		}
		f.SystemName = v
		return v, nil
	})
}

// askLicense collects the license key for the scaffolded LICENSE file.
// Empty input falls through to defaultLicense — pressing enter accepts
// the most common case, parallel to the flag default in
// bindYAMLAffectingFlags.
func askLicense(r *bufio.Reader, out io.Writer, f *config.RawFlags) error {
	return askWithDefault(r, out,
		fmt.Sprintf("License (mit|apache-2.0|gpl-3.0|bsd-2-clause|bsd-3-clause|unlicense) [default: %s]", defaultLicense),
		defaultLicense,
		func(v string) (string, error) {
			if !projectconfig.IsValidLicense(v) {
				return "", fmt.Errorf("must be one of mit, apache-2.0, gpl-3.0, bsd-2-clause, bsd-3-clause, unlicense")
			}
			f.License = v
			return v, nil
		})
}

func askArch(r *bufio.Reader, out io.Writer, f *config.RawFlags) error {
	return ask(r, out, "Architecture (monolith|multitier)", func(v string) (string, error) {
		if v != "monolith" && v != "multitier" {
			return "", fmt.Errorf("must be 'monolith' or 'multitier'")
		}
		f.Arch = v
		return v, nil
	})
}

func askRepoStrategy(r *bufio.Reader, out io.Writer, f *config.RawFlags) error {
	return ask(r, out, "Repo strategy (monorepo|multirepo)", func(v string) (string, error) {
		if v != "monorepo" && v != "multirepo" {
			return "", fmt.Errorf("must be 'monorepo' or 'multirepo'")
		}
		f.RepoStrategy = v
		return v, nil
	})
}

// askLang asks one language question that matches the chosen arch:
// monolith → --monolith-lang; multitier → --backend-lang. On multitier
// the frontend lang is hardcoded to typescript in applyDefaults (today's
// only valid value); when frontend-lang accepts more than typescript,
// add a matching prompt here.
func askLang(r *bufio.Reader, out io.Writer, f *config.RawFlags) error {
	validBackend := func(v string) bool {
		return v == "java" || v == "dotnet" || v == "typescript"
	}
	switch f.Arch {
	case "monolith":
		return ask(r, out, "Monolith language (java|dotnet|typescript)", func(v string) (string, error) {
			if !validBackend(v) {
				return "", fmt.Errorf("must be 'java', 'dotnet', or 'typescript'")
			}
			f.Lang = v
			return v, nil
		})
	case "multitier":
		return ask(r, out, "Backend language (java|dotnet|typescript)", func(v string) (string, error) {
			if !validBackend(v) {
				return "", fmt.Errorf("must be 'java', 'dotnet', or 'typescript'")
			}
			f.BackendLang = v
			return v, nil
		})
	}
	return fmt.Errorf("unreachable: arch %q passed validation but no lang branch", f.Arch)
}

func askProjectURL(r *bufio.Reader, out io.Writer, f *config.RawFlags) error {
	return ask(r, out, "GitHub Project URL", func(v string) (string, error) {
		if !strings.HasPrefix(v, "https://github.com/") {
			return "", fmt.Errorf("must be a https://github.com/... URL")
		}
		f.ProjectURL = v
		return v, nil
	})
}

// applyDefaults fills the fields the prompt does NOT ask for: tier paths
// to the flat scaffold layout, frontend-lang to typescript on multitier,
// and deploy to docker (cloud-run is in development; prompt this when a
// real choice exists).
// TODO: prompt for frontend-lang when more than typescript is valid.
// TODO: prompt for deploy when cloud-run ships.
func applyDefaults(f *config.RawFlags) {
	f.SystemTestPath = defaultSystemTestPath
	f.StubsPath = defaultStubsPath
	f.SimulatorsPath = defaultSimulatorsPath
	f.Deploy = projectconfig.DeployDocker
	switch f.Arch {
	case "monolith":
		f.SystemPath = defaultSystemPath
	case "multitier":
		f.BackendPath = defaultBackendPath
		f.FrontendPath = defaultFrontendPath
		f.FrontendLang = "typescript"
	}
}

// ask prints a single prompt and loops until accept returns nil. The
// caller's accept closure both validates and stores the value into the
// RawFlags. EOF (no more input — pipe closed, ^D, tests running out of
// fixture lines) is surfaced verbatim so the missing-file recovery can
// abort with the terse-error fallback rather than spin forever.
func ask(r *bufio.Reader, out io.Writer, label string, accept func(string) (string, error)) error {
	for {
		fmt.Fprintf(out, "  %s: ", label)
		line, err := r.ReadString('\n')
		if err != nil {
			return fmt.Errorf("read %s: %w", label, err)
		}
		v := strings.TrimSpace(line)
		if v == "" {
			fmt.Fprintln(out, "    value cannot be empty")
			continue
		}
		if _, err := accept(v); err != nil {
			fmt.Fprintf(out, "    %s\n", err)
			continue
		}
		return nil
	}
}

// askWithDefault is the askLicense-style variant: empty input is accepted
// and resolves to dflt rather than re-asking. Used for fields where a
// well-known default exists (license today; revisit if more such fields
// are added). Validation still runs against the resolved value.
func askWithDefault(r *bufio.Reader, out io.Writer, label, dflt string, accept func(string) (string, error)) error {
	for {
		fmt.Fprintf(out, "  %s: ", label)
		line, err := r.ReadString('\n')
		if err != nil {
			return fmt.Errorf("read %s: %w", label, err)
		}
		v := strings.TrimSpace(line)
		if v == "" {
			v = dflt
		}
		if _, err := accept(v); err != nil {
			fmt.Fprintf(out, "    %s\n", err)
			continue
		}
		return nil
	}
}
