// prompt.go drives the interactive flag-collection used when EnsureExists
// hits a missing gh-optivem.yaml on a TTY. The interactive surface is
// deliberately narrower than the non-interactive `config init` command:
// frontend-lang is hardcoded to `typescript`, deploy is hardcoded to
// `docker`, tier paths fall through to the defaults baked into
// resolvePathFlagsForYAML (the flat scaffold layout), and the user is
// asked only the fields with no good default — owner, repo, system-name,
// arch, repo-strategy, lang, project-url, license. A banner header
// prepended to the generated YAML points the operator at the defaulted
// fields and recommends running `gh optivem config validate` after
// review.
//
// Owner/repo are always asked: in environments with multiple accounts
// (personal + org), the `git remote get-url origin` of the current
// working directory is not a reliable proxy for the operator's intent.
//
// Each answer is validated against the same validator the `config init`
// flag path runs (see interactive-validation-parity feedback): format
// validators are the shared internal/config functions, and owner +
// project-URL existence are checked via config.CheckOwnerExists /
// config.CheckProjectExists. A bad value re-asks just that field rather
// than discarding the whole session.
package configinit

import (
	"bufio"
	"fmt"
	"io"
	"strings"

	"github.com/optivem/gh-optivem/internal/config"
	"github.com/optivem/gh-optivem/internal/projectconfig"
)

// defaultLicense is the prompt default for the license question. Matches
// bindYAMLAffectingFlags's --license default so the interactive and
// flag-driven paths produce identical YAML when the operator accepts the
// default.
const defaultLicense = projectconfig.LicenseMIT

// Banner is the comment header prepended to YAML generated by the
// interactive recovery flow. Single-sourced here so the prompt copy and
// the writer share one constant.
const Banner = `# gh-optivem.yaml — generated by ` + "`gh optivem config init`" + ` (interactive recovery).
# Review the following fields and run ` + "`gh optivem config validate`" + `:
#   - project.url
#       Your GitHub Projects board URL.
#   - repo_strategy
#       mono-repo (default) or multi-repo.
#   - system.lang / system.backend.lang
#       java, dotnet, or typescript.
#   - *.path fields
#       Assume the flat scaffold layout. Adjust to match your repo.
#   - license
#       SPDX-like key written to LICENSE. mit if you didn't pick one.
#   - deploy
#       docker today; cloud-run lands when its scaffold path stabilises.

`

// Prompt collects the slim interactive `config init` flag set and
// returns a populated RawFlags. Reads one line at a time from in;
// echoes prompts and validator errors to out. Re-asks the same field on
// validation failure; prior answers in the session are kept. Returns
// io.EOF (wrapped) if stdin closes mid-session, so callers can fall back
// to the terse error.
func Prompt(in io.Reader, out io.Writer) (*config.RawFlags, error) {
	r := bufio.NewReader(in)
	f := &config.RawFlags{}

	fmt.Fprintln(out, "No gh-optivem.yaml found — let's create one. Enter values for each prompt; bad input re-asks.")

	if err := askOwner(r, out, f); err != nil {
		return nil, err
	}
	if err := askRepo(r, out, f); err != nil {
		return nil, err
	}
	if err := askSystemName(r, out, f); err != nil {
		return nil, err
	}
	if err := askArch(r, out, f); err != nil {
		return nil, err
	}
	if err := askRepoStrategy(r, out, f); err != nil {
		return nil, err
	}
	if err := askLang(r, out, f); err != nil {
		return nil, err
	}
	if err := askProjectURL(r, out, f); err != nil {
		return nil, err
	}
	if err := askLicense(r, out, f); err != nil {
		return nil, err
	}

	applyDefaults(f)
	return f, nil
}

func askOwner(r *bufio.Reader, out io.Writer, f *config.RawFlags) error {
	return ask(r, out, "GitHub owner (user or org), e.g. acme", func(v string) (string, error) {
		if msg := config.ValidateOwnerFormat(v); msg != "" {
			return "", fmt.Errorf("%s", msg)
		}
		if err := config.CheckOwnerExists(v); err != nil {
			return "", err
		}
		f.Owner = v
		return v, nil
	})
}

func askRepo(r *bufio.Reader, out io.Writer, f *config.RawFlags) error {
	return ask(r, out, "Repository name (without owner prefix), e.g. page-turner", func(v string) (string, error) {
		if msg := config.ValidateRepoFormat(v); msg != "" {
			return "", fmt.Errorf("%s", msg)
		}
		f.Repo = v
		return v, nil
	})
}

// askSystemName collects the human-readable system label that drives
// templating (e.g. "Page Turner"). Validated with the same rule
// `gh optivem init` applies to its --system-name flag.
func askSystemName(r *bufio.Reader, out io.Writer, f *config.RawFlags) error {
	return ask(r, out, `System name, e.g. "Page Turner"`, func(v string) (string, error) {
		if msg := config.ValidateSystemName(v); msg != "" {
			return "", fmt.Errorf("%s", msg)
		}
		f.SystemName = v
		return v, nil
	})
}

// askLicense collects the license key for the scaffolded LICENSE file.
// Empty input falls through to defaultLicense — pressing enter accepts
// the most common case, parallel to the flag default in
// bindYAMLAffectingFlags.
func askLicense(r *bufio.Reader, out io.Writer, f *config.RawFlags) error {
	return askWithDefault(r, out,
		fmt.Sprintf("License (mit|apache-2.0|gpl-3.0|bsd-2-clause|bsd-3-clause|unlicense) [default: %s]", defaultLicense),
		defaultLicense,
		func(v string) (string, error) {
			if !projectconfig.IsValidLicense(v) {
				return "", fmt.Errorf("must be one of mit, apache-2.0, gpl-3.0, bsd-2-clause, bsd-3-clause, unlicense")
			}
			f.License = v
			return v, nil
		})
}

func askArch(r *bufio.Reader, out io.Writer, f *config.RawFlags) error {
	return ask(r, out, "Architecture (monolith|multitier), e.g. monolith", func(v string) (string, error) {
		if msg := config.ValidateArch(v); msg != "" {
			return "", fmt.Errorf("%s", msg)
		}
		f.Arch = v
		return v, nil
	})
}

func askRepoStrategy(r *bufio.Reader, out io.Writer, f *config.RawFlags) error {
	return ask(r, out, "Repo strategy (monorepo|multirepo), e.g. monorepo", func(v string) (string, error) {
		if msg := config.ValidateRepoStrategy(v); msg != "" {
			return "", fmt.Errorf("%s", msg)
		}
		f.RepoStrategy = v
		return v, nil
	})
}

// askLang asks one language question that matches the chosen arch:
// monolith → --monolith-lang; multitier → --backend-lang. On multitier
// the frontend lang is hardcoded to typescript in applyDefaults (today's
// only valid value); when frontend-lang accepts more than typescript,
// add a matching prompt here.
func askLang(r *bufio.Reader, out io.Writer, f *config.RawFlags) error {
	switch f.Arch {
	case "monolith":
		return ask(r, out, "Monolith language (java|dotnet|typescript), e.g. java", func(v string) (string, error) {
			if msg := config.ValidateBackendLang(v); msg != "" {
				return "", fmt.Errorf("%s", msg)
			}
			f.Lang = v
			return v, nil
		})
	case "multitier":
		return ask(r, out, "Backend language (java|dotnet|typescript), e.g. java", func(v string) (string, error) {
			if msg := config.ValidateBackendLang(v); msg != "" {
				return "", fmt.Errorf("%s", msg)
			}
			f.BackendLang = v
			return v, nil
		})
	}
	return fmt.Errorf("unreachable: arch %q passed validation but no lang branch", f.Arch)
}

// askProjectURL collects the GitHub Project URL. Empty input is accepted
// — mirrors the flag-path semantics where empty --project-url lets
// `gh optivem init` Path A auto-create a board on first run. A non-empty
// value is format-validated (canonical orgs|users/<owner>/projects/<n>
// shape) and then existence-checked via config.CheckProjectExists so a
// typo'd URL re-asks just this field rather than landing in the YAML.
func askProjectURL(r *bufio.Reader, out io.Writer, f *config.RawFlags) error {
	return askWithDefault(r, out,
		"GitHub Project URL (press enter to auto-create on first `gh optivem init`), e.g. https://github.com/orgs/acme/projects/1",
		"",
		func(v string) (string, error) {
			if msg := config.ValidateProjectURLFormat(v); msg != "" {
				return "", fmt.Errorf("%s", msg)
			}
			if err := config.CheckProjectExists(v); err != nil {
				return "", err
			}
			f.ProjectURL = v
			return v, nil
		})
}

// applyDefaults fills the fields the prompt does NOT ask for and that
// are NOT already defaulted by config.resolvePathFlagsForYAML (tier
// paths). Today that's frontend-lang on multitier (typescript is the
// only valid value) and deploy (docker; cloud-run is in development —
// prompt for it when a real choice exists).
// TODO: prompt for frontend-lang when more than typescript is valid.
// TODO: prompt for deploy when cloud-run ships.
func applyDefaults(f *config.RawFlags) {
	f.Deploy = projectconfig.DeployDocker
	if f.Arch == "multitier" {
		f.FrontendLang = "typescript"
	}
}

// ask prints a single prompt and loops until accept returns nil. The
// caller's accept closure both validates and stores the value into the
// RawFlags. EOF (no more input — pipe closed, ^D, tests running out of
// fixture lines) is surfaced verbatim so the missing-file recovery can
// abort with the terse-error fallback rather than spin forever.
func ask(r *bufio.Reader, out io.Writer, label string, accept func(string) (string, error)) error {
	for {
		fmt.Fprintf(out, "  %s: ", label)
		line, err := r.ReadString('\n')
		if err != nil {
			return fmt.Errorf("read %s: %w", label, err)
		}
		v := strings.TrimSpace(line)
		if v == "" {
			fmt.Fprintln(out, "    value cannot be empty")
			continue
		}
		if _, err := accept(v); err != nil {
			fmt.Fprintf(out, "    %s\n", err)
			continue
		}
		return nil
	}
}

// askWithDefault is the askLicense-style variant: empty input is accepted
// and resolves to dflt rather than re-asking. Used for fields where a
// well-known default exists (license today; revisit if more such fields
// are added). Validation still runs against the resolved value.
func askWithDefault(r *bufio.Reader, out io.Writer, label, dflt string, accept func(string) (string, error)) error {
	for {
		fmt.Fprintf(out, "  %s: ", label)
		line, err := r.ReadString('\n')
		if err != nil {
			return fmt.Errorf("read %s: %w", label, err)
		}
		v := strings.TrimSpace(line)
		if v == "" {
			v = dflt
		}
		if _, err := accept(v); err != nil {
			fmt.Fprintf(out, "    %s\n", err)
			continue
		}
		return nil
	}
}
